### ISSUE TITLE
working in mode:development but  not 'production'

### ISSUE THREAD

**Issue by davidGrocerKey** [waysact/webpack-subresource-integrity#116]
I have webpack bundling 3 files and using your plugin with the webpack-manifest plugin to pass these files an integrity Hash.
My issue is that when this is run on mode:production, 1 (sometimes 2) of the files get this error:
`Failed to find a valid digest in the 'integrity' attribute for resource... `
is there something specific I have to do for production mode which may be minifying or changing the files somehow?

it works fine in development mode

**Comment by jscheid** [comment]
There's nothing special you need to do. In fact we recommend to run this plugin _only_ in production mode, since in development mode it can get in the way of hot reloading and also is not usually needed.

Happy to help you debug this but I'll need some more info, ideally a small test case. Can you boil it down to a standalone repository that throws the error when it's built?

**Comment by jscheid** [comment]
I'm closing this, feel free to reopen when you have more information to share.
