### ISSUE TITLE
Compatibility with optimize-css-assets-webpack-plugin

### ISSUE THREAD

**Issue by hitchcott** [waysact/webpack-subresource-integrity#47]
Whenever I use this plugin in combination with `optimize-css-assets-webpack-plugin`, the resulting `link` tag generates the incorrect `integrity` attribute, and therefore prevents the CSS from loading in browser:

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://xxx/style.415f2b53c2098ba7dfd1271ff3ea863b.css' with computed SHA-256 integrity 'TSiEV9m8u3ydiUrNtjVJ2VK3P/LRhVT1v11HpKQFCjU='. The resource has been blocked
```

Disabling the `optimize-css-assets-webpack-plugin` plugin fixes the error.

```javascript
    new OptimizeCssAssetsPlugin(), // comment-out to fix build
    new SriPlugin({ hashFuncNames: ['sha256', 'sha512'] }),
```

Versions
```json
    "optimize-css-assets-webpack-plugin": "^2.0.0",
    "webpack": "^2.6.1",
    "webpack-subresource-integrity": "^1.0.0-rc.1"
```

I'll try putting together a reproduction tomorrow.

**Comment by jscheid** [comment]
Hi,

The other plugin performs the optimization in the `emit` phase, and as such is incompatible with webpack-subresource-integrity. By that point the integrity hashes have already been computed, and so any changes to the asset contents will cause breakage.

I think the correct fix here is to ask the authors of optimize-css-assets-webpack-plugin to perform the optimization in the `optimize` phase instead, perhaps using the [optimize-chunk-assets](https://webpack.github.io/docs/plugins.html#optimize-chunk-assets-async) hook.

Let me know in case the other plugin has a good reason for hooking into the `emit` phase instead of the `optimize` phase and I'm happy to take another look at this.

**Comment by NMFR** [comment]
Would [`optimize-assets`](https://webpack.github.io/docs/plugins.html#optimize-assets-async) also work?

**Comment by jscheid** [comment]
@NMFR thanks for taking a look at this. Yes I think that would work as well. I've made an integration test that you can use to verify your fix: https://github.com/jscheid/wsi-issue-47

**Comment by NMFR** [comment]
Solved. @jscheid thanks for the help.
