### ISSUE TITLE
`crossOriginLoading: false` defaults to `anonymous`

### ISSUE THREAD

**Issue by Schlesiger** [waysact/webpack-subresource-integrity#64]
It appears `crossOriginLoading: false` doesn't work. When I set the value to false, [a valid option](https://github.com/webpack/docs/wiki/configuration#outputcrossoriginloading), I still receive the warning `WARNING in webpack-subresource-integrity: Set webpack option output.crossOriginLoading when using this plugin.`. Perhaps `webpack-subresource-integrity` is checking for a falsy value, instead of a more specific `crossOriginLoading !== undefined && crossOriginLoading !== null`? If I ignore the warning and leave the `crossOriginLoading` as `false`, it defaults to `anonymous`.

**Comment by jscheid** [comment]
It's a valid option to Webpack, but it's not an acceptable value to this plugin because SRI [requires crossOrigin to be set](https://w3c.github.io/webappsec-subresource-integrity/#cross-origin-data-leakage).

I'm thinking about changing the wording of the warning message to be more explicit, perhaps "Set webpack option output.crossOriginLoading to a value other than `false` when using this plugin". Do you think that would be a good change?

**Comment by Schlesiger** [comment]
Oh my apologies; I didn't think it would matter if I was using `cors` already. Changing the wording would help. Also, while the  W3C `Subresource Integrity` link _is_ at the top of the `README`, perhaps following the `crossOriginLoading` description an additional link to the `#cross-origin-data-leakage` tag could help inform folks like me. :-) Thanks!

**Comment by jscheid** [comment]
All good, no harm done 😄 How about this?

```
SRI requires a cross-origin policy, defaulting to "anonymous".
Set Webpack option output.crossOriginLoading to a value other than false
to make this warning go away. 
See https://w3c.github.io/webappsec-subresource-integrity/#cross-origin-data-leakage
```
